# TSP problem

In [17]:
import numpy as np
import scipy.spatial.distance as spy

In [71]:
X = np.array([[1.0, 2.0],
[4.0, 5.0],[3,6],[1,1]])

In [80]:
X

array([[1., 2.],
       [4., 5.],
       [3., 6.],
       [1., 1.]])

In [81]:
Solution = np.array([4,2,1,3])

In [74]:
Solution


array([4, 2, 1, 3])

In [76]:
Dist=spy.cdist(X,X)

In [77]:
Dist

array([[0.        , 4.24264069, 4.47213595, 1.        ],
       [4.24264069, 0.        , 1.41421356, 5.        ],
       [4.47213595, 1.41421356, 0.        , 5.38516481],
       [1.        , 5.        , 5.38516481, 0.        ]])

In [83]:
def cost_function(X,Sol):
    cost=[]
    dist=spy.cdist(X,X)
    for i in range(len(Sol)-1):
        index=sol[i:i+2]
        c=dist[index[0]-1,index[1]-1]
        cost.append(c)
    # Close the trip
    index=sol[0:len(Sol)]
    

    return cost
    

In [84]:
Cost_function(X,Solution)

[5.0, 4.242640687119285, 4.47213595499958]

In [88]:
Solution

array([4, 2, 1, 3])

In [42]:
index=Solution[0:2]
index

array([3, 1])

In [53]:
C=Dist[index[0]-1,index[1]-1]

In [54]:
Cost.append(C)

In [55]:
Cost

[4.47213595499958]